def recipes():
    all_recipes =[ {
            'name':'fried rice',
            'slug':'fried-rice',
            'preptime':'10 mins',
            'cooktime':'20 mins',
            'serving':'2 servings',
            'tags':['lunch','rice','food'],
            'description':'This classic Vegetable Fried Rice recipe is made with a hearty mix of fresh veggies, green onions, seasonings and spices for an incredibly flavorful fried rice dish. Hands-down this is one of our favorite Chinese-inspired recipes. Not only is Veg Fried Rice amazingly easy to make from scratch, it’s a naturally vegan dish that’s as good for you as it is delicious to eat. You can even tweak vegetable fried rice to be gluten-free simply by omitting soy sauce or using tamari.',
            'ingredients':['1 cup basmati rice or long grained rice: 190 to 200 grams',
                             '1/2 cup finely chopped carrots','1/4 to 1/2 cup finely chopped cabbage',
                             '3 tablespoons oil','3 tablespoons soy sauce','1 teaspoon rice wine or rice vinegar',
                             '2 tablespoons chopped spring onions greens',
                             '1 star anise',
                             '1/4 cup chopped bell pepper',
                             '1 cup chopped button mushrooms'],
            'steps':['Heat oil in a wok or a pan. First add the star anise and fry for a few seconds or until the oil becomes fragrant.',
                     'Add the garlic, ginger and sauté for some seconds. No need to brown the garlic.',
                     'Add the spring onions whites and sauté for about 2 minutes.',
                     'Then add finely chopped french beans.',
                     'Stir fry french beans for 2 to 3 minutes over medium to medium-high heat.',
                     'The vegetables have to be stir-fried, until they are almost cooked and yet retain their crunchiness and crispiness. Stir-frying vegetables on high heat takes about 4 to 6 minutes.',
                     'Add the soy sauce, salt and pepper. Stir quickly and add cooked and cooled rice. Stir fry for a few minutes until the sauce has coated the rice well. Keep a check when adding salt, as soy sauce already has salt in it.',
                     'Serve the fried rice hot as it is or with with your favorite Chinese side.'],
            'image':'fried-rice.jpg'
        },
        {
            'name':'white sauce pasta',
            'slug':'white-sauce-pasta',
            'preptime':'15 mins',
            'cooktime':'10 mins',
            'serving':'1 serving',
            'tags':['snacks','pasta','food'],
            'description':'White sauce pasta is one of the easiest pasta recipes that you can make. It is also one of the most popular pasta recipes. You can make the classic white sauce pasta or make it more colorful and nutritious by adding some vegetables.',
            'ingredients':['2 tablespoons Butter','1 tablespoon whole wheat flour or 2 tablespoons all-purpose flour',
                           '1 cup chilled milk or 250 ml chilled milk',
                           '1/4 teaspoon black pepper powder or add as required',
                           '1 cup penne pasta or 100 grams penne pasta',
                           '4 cups water',
                           '1/4 teaspoon salt or add as required'],
            'steps':['Cook the pasta on a medium to high flame.','Then add them to the white sauce.',
                     'Add ¼ teaspoon each of dried oregano, dried basil and dried thyme. You can add your choice of herbs. At this step you can even add some steamed or cooked or sauteed or roasted veggies.',
                     'Serve white sauce pasta garnished with some fresh herbs like parsley, chives or dill. You can also garnish with some grated cheddar cheese.'],
            'image':'white-sauce-pasta.jpg'
        },
       {
            'name':'cheese corn sandwich',
            'slug':'cheese-corn-sandwich',
            'preptime':'10 mins',
            'cooktime':'20 mins',
            'serving':'3 servings',
            'tags':['snacks','sandwich','food'],
            'ingredients':['2 to 3 teaspoons olive oil or butter','1 boiled medium sweet corn cob','2 small tomatoes - finely chopped',
                           '3 to 4 tablespoons grated cheddar cheese','1 tablespoon oil',
                           '3 cups water','7 to 8 basil leaves','6 sandwich bread slices or large bread slices'],
            'steps':['Slice the edges of bread if you prefer. Spread butter evenly on all the slices. Make sure the butter covers the entire of bread.',
                     'Stuff this corn-tomato-cheese filling on the buttered bread. Cover the sandwiches with the remaining buttered slices.',
                     'Place them in a preheated toaster or grill. Then grill or toast corn sandwich for 2 to 3 minutes or till the bread gets toasted well and golden.',
                     'You can also grill the sandwiches in the oven.',
                     'Serve corn sandwich hot or warm with tomato ketchup or mayonnaise. You can also serve them with a side of french fries or potato wafers or potato wedges.'],
            'image':'cheese-corn-sandwich.jpg'
        },
       {
            'name':'pav bhaji',
            'slug':'pav-bhaji',
            'preptime':'20 mins',
            'cooktime':'20 mins',
            'serving':'5 servings',
            'tags':['lunch','pav bhaji','street food'],
            'description':'Pav Bhaji is a hearty, delightful, satisfying meal of mashed vegetable gravy with fluffy soft buttery dinner rolls served with a side of crunchy piquant onions, tangy lemon and herby coriander.',
            'ingredients':['1 cup chopped carrot','3 potatoes','2.25 to 2.5 cups water',
                           '1 cup green peas','3 tablespoons Butter','2 teaspoons Ginger Garlic Paste','1 teaspoon turmeric powder',
                           'salt as required','2 to 3 tablespoons Pav Bhaji Masala'],
            'steps':['Heat a skillet or a shallow frying pan. Keep the flame to a low and then add butter.',
                     'When the butter begins to melt, add a bit of pav bhaji masala. You can skip pav bhaji masala if you want.',
                     'Mix the pav bhaji masala very well with a spoon or spatula.',
                     'Then place the pav on the butter.',
                     'Rotate the pav all over the melted butter so that the pav absorbs the butter.',
                     'Now turn over the pav and rotate them on the tawa so that the second side absorbs the butter. Add more butter if required.',
                     'You can turn over and toast them more if required. Then remove in a plate and keep aside.'],
            'image':'pav-bhaji.jpg'
        },{
            'name':'eggles chocolate cake',
            'slug':'eggless-chocolate-cake',
            'preptime':'10 mins',
            'cooktime':'20 mins',
            'serving':'12 slices',
            'tags':['dessert','sweet','cake'],
            'description':'This easy (one-bowl!) Eggless Chocolate Cake is a simple vegan recipe you are sure to come back to time and again. Unbelievably soft and light, you would not believe that this decadent, chocolatey sponge cake is actually made with healthy whole wheat flour.',
            'ingredients':['1 cup whole wheat flour','3 tablespoons cocoa powder','½ teaspoon baking soda',
                           '¼ cup sunflower oil','3 tablespoons cocoa powder','¼ cup raw sugar or white sugar','▢¼ cup Almond Milk or any nut milk'],
            'steps':['Sieve whole wheat flour, salt, baking soda in a plate or bowl. Before sifting keep a plate, bowl or tray below the sieve. Use a good quality cocoa powder.',
                     'Place the sifted dry ingredients aside.','In another pan or bowl, take the raw sugar.',
                     'Add cold water and stir with small whisk until all of the sugar dissolves.',
                     'Pour the sunflower oil. Stir briskly so that everything is mixed well and you get a homogenous mixture.',
                     'Next add the lemon juice and vanilla extract. Stir well again.',
                     'Tap the sides of the pan so that the extra air bubbles are let out.',
                     'Bake in a preheated oven for 200 degrees Celsius (392 degrees Fahrenheit) for 35 to 40 mins. Since temperatures vary from oven to oven, do keep a check.',
                     'For baking in a convection mode of microwave oven, preheat the oven at 180 degrees celsius (356 degrees Fahrenheit) for 15 minutes. Then bake the cake at 180 degrees celsius (356 degree Fahrenheit) for 30 to 35 minutes.',
                     'If the toothpick is sticky, then place the cake back in the oven and continue to bake for some more minutes. Before frosting let the chocolate cake cool completely.',
                     'While still hot, pour the frosting on the chocolate cake on the top and sides of the cake. Spread it evenly with an offset spatula. You can also slice the chocolate cake in halve and spread frosting in the center and then on the top.',
                     'Usually I wrap a medium sized plate with aluminium foil and then keep the cake on it. This make the frosting work easier.',
                     'Keep the chocolate cake covered in the fridge for the frosting to set for a couple of hours. You can use a dome shaped bowl to cover the cake. Make sure the there is enough space between the cake and the bowl which you are using for covering the cake.',
                     'Slice and serve eggless chocolate cake as a sweet dessert.'],
            'image':'eggles-chocolate-cake.jpg'
        },{
            'name':'veg noodles',
            'slug':'veg-noodles',
            'preptime':'15 mins',
            'cooktime':'15 mins',
            'serving':'3 servings',
            'tags':['snacks','chinese','fast food'],
            'description':'This delish Veg Noodles recipe is a Chinese style recipe. Veg Noodles are stir-fried noodles made with loads of mix vegetables and seasoned with soy sauce, ginger, garlic and celery.',
            'ingredients':['200 grams noodles','5 cups water','½ teaspoon salt','½ cup shredded carrots','8 to 10 french beans',
                           '⅓ cup sliced capsicum','1 teaspoon finely chopped ginger','1 teaspoon rice vinegar','1 to 2 tablespoon soy sauce'],
            'steps':['First boil water in a pan with salt and oil.','Heat oil in a wok or pan.','First add the garlic and ginger and stir fry or sauté on low to medium-low heat for some seconds.',
                     'Increase the heat to a high and add the chopped spring onions.',
                     'Keep on stirring continuously and stir fry the onions till they become translucent.',
                     'Continue to toss and stir fry on a high flame till the veggies are almost cooked.',
                     'You can also decrease the flame if the heat becomes too much too handle and then stir fry the veggies on a medium flame.',
                     'Some crunch should be there in the vegetables, so don’t cook the vegetables till they become completely soft.',
                     'Add cooked noodles. Keep on tossing and stirring till the veggies are mixed well with noodles for a minute or two. Switch off the heat.',
                     'Check the taste and add more salt, black pepper or soy sauce if required to the stir-fried veg noodles.'],
            'image':'vegetable-noodles.jpg'
        },{
            'name':'Oven Baked Sweet Potato Fries',
            'slug':'Oven-Baked-Sweet-Potato-Fries',
            'preptime':'10 mins',
            'cooktime':'20 mins',
            'serving':'4 to 6 servings',
            'description':'These oven baked sweet potato fries are so addictive! Wedges of sweet potatoes, tossed with oil, sprinkled with spices, and baked at high heat until browned and crispy at the edges.',
            'tags':['snacks','potato','chinese'],
            'ingredients':['2 pounds orange fleshed sweet potatoes (about 3 large)','3 tablespoons extra virgin olive oil',
                           '1 1/2 teaspoons kosher salt','1 to 2 tablespoons spice or spice combination of your '
                                                         'choice: chipotle powder, smoked paprika, '
                                                         'Chinese five-spice, pumpkin pie spice, garam masala, '
                                                         'Cajun seasoning, etc.'],
            'steps':['Peel the sweet potatoes and cut off the ends. Cut the potatoes in half lengthwise and then, if they are very long, in half crosswise. Cut each piece into 1/4 to 1/2-inch thick wedges.',
                     'Put the sweet potatoes into a large bowl and add the oil. Mix well to combine. Sprinkle with salt and spices of your choice.',
                     'Remove the preheated baking sheet from the oven. Carefully spread the sweet potatoes out in a single layer on the baking sheet.',
                     'Bake for 15 to 25 minutes. After the first 10 minutes, remove the baking sheet from the oven and use tongs to turn over all of the sweet potato pieces.',
                     'When ready let the fries cool for 5 minutes before serving.'],
            'image':'potato-fries.jpg'

        },{
            'name':'hot chocolate',
            'slug':'hot-chocolate',
            'preptime':'10 mins',
            'cooktime':'5 mins',
            'serving':'2 servings',
            'tags':['drinks','chocolate','milk'],
            'description':'This adults-only boozy hot chocolate is rich, creamy, and very decadent. With endless varieties of add-ins, you’ll never get tired of trying this chocolatey recipe.',
            'ingredients':['2 cups whole milk','6 ounces semisweet chocolate, finely chopped',
                           '3 ounces liquor of choice, such as bourbon, rum, or a cream liqueur',
                           '1/2 teaspoon vanilla extract','Optional toppings:'
                                                          'mini marshmallows or whipped cream, chocolate shavings, '
                                                          'sprinkles'],
            'steps':['Warm the milk in a medium saucepan over medium-low heat until it begins to barely simmer but not boil',
                     'Add in the chopped chocolate and whisk until combined and smooth, about 5 minutes.',
                     'Remove from the heat and stir in the liquor, vanilla extract, and salt.',
                     'Let sit to cool to a safe drinking temperature for about 5 minutes (still hot but not burning). '
                     'Pour into heatproof mugs. If a skin forms while cooling, just whisk it for a few seconds to '
                     'reincorporate.'],
            'image':'hot-chocolate.jpg'
        },{
            'name':'fried spring rolls',
            'slug':'fried spring rolls',
            'preptime':'45 mins',
            'cooktime':'40 mins',
            'serving':'45 servings',
            'tags':['snacks','chinese','rolls'],
            'description':'Fried spring rolls are filled with juicy shredded pork, cabbage, carrots, and mushrooms to create slender, smooth, and delicate packages. I fry them until golden and the wrappers are shatteringly crispy at first bite.',
            'ingredients':['8 dried shiitake mushrooms','1 pound pork loin or tenderloin',
                           '1 tablespoon sesame oil','4 teaspoons soy sauce','1/2 medium head napa cabbage, thinly sliced (about 6 cups)',
                           '50 to 60 (6-inch) square spring roll wrappers','Chinkiang vinegar or black vinegar, to serve'],
            'steps':['Set two sheet pans by the stove for you to transfer the meat and vegetables onto. '
                     'Place the dried mushrooms into a medium bowl. '
                     'Add enough hot water to cover the mushrooms.',
                     'Cut the pork against the grain into 1/4-inch thick 2 1/2 to 3-inch long matchsticks and put them into a medium bowl',
                     'In large nonstick skillet over medium-high heat, add 2 tablespoons of oil. When hot, add the pork and toss to coat with oil.',
                     'In the same skillet used to cook the carrots, add 1 tablespoon of oil, the napa cabbage, and the remaining 1/2 teaspoon of salt',
                     'Wrapping spring rolls is basically like wrapping burritos. Place one spring roll wrapper on the board in front of you with the corners facing 3, 6, 9 and 12 o’clock.',
                     'Working in 3 or 4 batches, gently slide the spring rolls into the hot oil. Cook, stirring occasionally with a spider or large slotted spoon to make sure that all sides are cooking evenly, until the spring rolls are golden brown, 1 1/2-2 minutes.'],
            'image':'fried-spring-rolls.jpg'
        }
       
    
  
    ]
    return all_recipes
